/** @type {import('prettier').Config} */
const config = {
	'editor.formatOnSave': true,
	'editor.formatOnType': true,
	endOfLine: 'lf',
	semi: false,
	singleQuote: true,
	useTabs: true,
	tabWidth: 2,
	trailingComma: 'es5',
	printWidth: 120,
	importOrder: [
		'^(react/(.*)$)|^(react$)',
		'<THIRD_PARTY_MODULES>',
		'',
		'^@/types$',
		'^@/types/(.*)$',
		'^@/config$',
		'^@/config/(.*)$',
		'^@/paths$',
		'^@/routes$',
		'^@/pages/(.*)$',
		'^@/data/(.*)$',
		'^@/lib/(.*)$',
		'^@/contexts/(.*)$',
		'^@/hooks/(.*)$',
		'^@/providers/(.*)$',
		'^@/components/(.*)$',
		'^@/styles/(.*)$',
		'',
		'^[./]',
	],
	plugins: ['@ianvs/prettier-plugin-sort-imports'],
}

export default config
